REDIS:
  ENABLED: true
  HOST: '172.18.0.1'
  PORT: '25574'
  PASSWORD: 'P55w0rd'
  DATABASE: 0
  POOL:
    MAX_TOTAL: 20
    MAX_IDLE: 10
    MIN_IDLE: 2
  CACHE:
    TTL: 3600
    LEADERBOARD_SIZE: 100

MONGO:
  URI-MODE: true
  NORMAL:
    HOST: 127.0.0.1
    PORT: 27017
    DATABASE: GroupStats
    AUTHENTICATION:
      ENABLED: false
      USERNAME: ''
      PASSWORD: ''
  URI:
    DATABASE: 'groupstats'
    CONNECTION_STRING: 'mongodb://admin:p55W0rdsss@172.18.0.1:25575/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.0'

CACHE_STRATEGY: REDIS_MONGO
UPDATE_TIMER: 1
DEBUG: true

SERVER:
  NAME: 'BedWars-1'  
