name: GroupStats
version: '${project.version}'
main: me.infinity.groupstats.GroupStatsPlugin
api-version: 1.19
authors: [ Infinity, HussainBeast ]
description: Group statistics plugin
website: https://github.com/yourusername/groupstats

commands:
  gstest:
    description: Test command for group statistics
    usage: /<command>
  gsstatus:
    description: View Redis and server network status
    usage: /<command>
permissions:
  groupstats.test:
    description: Allows use of the gstest command
    default: true
  groupstats.admin:
    description: Allows use of admin commands
    default: true
